/* Dependency-free release bundler. Source files stay editable; index.html is generated. */
import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {gzipSync} from 'node:zlib';
const root=path.dirname(fileURLToPath(import.meta.url));
const modules=[['runtime','app-runtime.js',true],['sdk','vendor/supabase-2.117.2.js',true],
  ['gestures','home-gestures.js'],['kitchen-catalog','kitchen-recipes.js'],['kitchen-api','kitchen-api.js'],
  ['kitchen','kitchen.js'],['fat','fat-loss.js'],['rewards','fat-rewards.js'],['access','device-access.js',true],['push','web-push.js'],['notifications','notifications.js'],['app','app.js',true],['theme','ui-theme.js']];
const styles=['fat-loss.css','fat-rewards.css','ui-theme.css','kitchen.css','web-push.css','device-access.css','notifications.css'];
export async function bundle({build,updatedAt,sdkSource}={}) {
  const previous=JSON.parse(await fs.readFile(path.join(root,'version.json'),'utf8').catch(()=>'{}'));
  const now=new Date(),day=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit'}).format(now).replaceAll('-','');
  build ||= previous.build?.startsWith(day+'.')?`${day}.${Number(previous.build.split('.')[1])+1}`:`${day}.1`;
  updatedAt ||= now.toISOString();
  if(!/^\d{8}\.\d+$/.test(build) || !Number.isFinite(Date.parse(updatedAt)))throw Error('Invalid release metadata');
  const displayTime=new Intl.DateTimeFormat('zh-CN',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(updatedAt));
  const read=file=>fs.readFile(path.join(root,file),'utf8');
  const safe=text=>text.replace(/<\/script/gi,'<\\/script');
  let scripts=`<script data-points-asset="startup">${safe(await read('startup.js'))}</script>\n`;
  for(const [id,file,required=false] of modules) {
    const source=id==='sdk' && sdkSource?sdkSource:await read(file);
    new Function(source); // Fail the build rather than shipping a syntax error.
    scripts+=`<script data-points-asset="${id}">if(window.PointsStartup.canStart()){try{\n${safe(source)}\n}catch(error){window.PointsStartup.fail(${JSON.stringify(id)},error,${required});}}</script>\n`;
  }
  scripts+=`<script>window.PointsStartup.finish();</script>\n<script>${safe(await read('updates.js'))}</script>`;
  const css=(await Promise.all(styles.map(read))).join('\n');
  const template=await read('index.source.html');
  const html='<!-- Generated by points/build.mjs; edit index.source.html and module sources, then rebuild. -->\n'+template.replace('<!-- POINTS_STYLES -->',()=>`<style data-points-bundle="styles">${css}</style>`)
    .replace('<!-- POINTS_SCRIPTS -->',()=>scripts).replaceAll('__POINTS_BUILD__',build).replaceAll('__POINTS_UPDATED_AT__',displayTime)
    .replace(/\r\n?/g,'\n');
  return {html,build,updatedAt,worker:(await read('sw.source.js')).replaceAll('__POINTS_BUILD__',build)};
}
async function writeBatches(file,text) {
  const handle=await fs.open(path.join(root,file),'w');
  try {const lines=text.split('\n');for(let i=0;i<lines.length;i+=200)await handle.write(lines.slice(i,i+200).join('\n')+(i+200<lines.length?'\n':''));}
  finally {await handle.close();}
}
if(process.argv[1] && path.resolve(process.argv[1])===fileURLToPath(import.meta.url)) {
  const result=await bundle({build:process.argv[2],updatedAt:process.argv[3]});
  await writeBatches('index.html',result.html);await writeBatches('sw.js',result.worker);
  await writeBatches('version.json',JSON.stringify({build:result.build,updatedAt:result.updatedAt},null,2)+'\n');
  console.log(`Release ${result.build}: ${Buffer.byteLength(result.html)} bytes, gzip ${gzipSync(result.html).length} bytes; 0 external startup JS/CSS requests.`);
}
