window.SPEAK_DAILY_GROUPS = ["理解回应", "约计划", "请求澄清", "轻松社交", "帮忙行动", "道歉缓和", "表达观点", "转场接话", "情绪感受", "赞美鼓励", "餐厅咖啡", "购物付款", "出行问路", "电话消息", "工作沟通", "争取时间", "建议决定", "边界拒绝", "熟人闲聊", "小问题处理", "同意不同意", "语气程度", "家里生活", "健康状态", "网络科技", "金钱账单", "惊讶反应", "结束对话", "安慰支持", "临场救急"];

window.SPEAK_DAILY_PHRASES = [
  {id:"understand-01",group:"理解回应",en:"I got it.",zh:"我明白了。",scene:"别人交代任务、规则或安排时。",tip:"I got 连起来，重音落在 got，it 轻轻收尾。",example:"A: Send this before noon. B: I got it.",keys:["got","it"]},
  {id:"understand-02",group:"理解回应",en:"Gotcha.",zh:"懂了，收到。",scene:"熟人之间快速回应，比 I understand 更口语。",tip:"像 got-chuh，一口气说完，不要拖长。",example:"A: Turn left after the bank. B: Gotcha.",keys:["gotcha"]},
  {id:"understand-03",group:"理解回应",en:"Makes sense.",zh:"说得通，有道理。",scene:"别人解释原因后，你表示理解。",tip:"重音在 sense，makes 可以弱读。",example:"A: Traffic was terrible. B: Makes sense.",keys:["makes","sense"]},
  {id:"understand-04",group:"理解回应",en:"Fair enough.",zh:"也行，可以理解。",scene:"你不完全同意，但接受对方理由。",tip:"fair enough 连读，enough 的 n 要清楚。",example:"A: I need more time. B: Fair enough.",keys:["fair","enough"]},
  {id:"understand-05",group:"理解回应",en:"I see what you mean.",zh:"我懂你的意思。",scene:"对方表达观点后，你表示跟上了。",tip:"see 和 mean 稍重，中间保持轻快。",example:"A: It feels too formal. B: I see what you mean.",keys:["see","mean"]},
  {id:"understand-06",group:"理解回应",en:"That works for me.",zh:"这个对我可以。",scene:"确认时间、方案、安排都可用。",tip:"works 是核心重音，for me 轻一点。",example:"A: How about Friday? B: That works for me.",keys:["works","me"]},
  {id:"understand-07",group:"理解回应",en:"I'm with you.",zh:"我跟得上，我同意。",scene:"会议、聊天中表示理解或站在同一边。",tip:"I'm with 连起来，with 的 th 不要吞掉。",example:"A: We should keep it simple. B: I'm with you.",keys:["with","you"]},
  {id:"understand-08",group:"理解回应",en:"Good to know.",zh:"知道了，挺有用。",scene:"别人补充一个实用信息时。",tip:"good to 像 good-du，know 收住。",example:"A: They close at six. B: Good to know.",keys:["good","know"]},
  {id:"understand-09",group:"理解回应",en:"That explains it.",zh:"这就解释得通了。",scene:"听到原因后，一下子明白情况。",tip:"explains 是主重音，it 很轻。",example:"A: The train was delayed. B: That explains it.",keys:["explains","it"]},
  {id:"plan-01",group:"约计划",en:"Sounds good.",zh:"听起来不错，就这么定。",scene:"答应建议、确认安排时。",tip:"sounds 的 z 音带出来，good 短促。",example:"A: Let's meet at two. B: Sounds good.",keys:["sounds","good"]},
  {id:"plan-02",group:"约计划",en:"I'm down.",zh:"我可以，我愿意。",scene:"朋友邀请你参加活动时。",tip:"down 是重音，语气轻松。",example:"A: Want to grab dinner? B: I'm down.",keys:["down"]},
  {id:"plan-03",group:"约计划",en:"Let's play it by ear.",zh:"到时候看情况吧。",scene:"计划未定，先保持灵活。",tip:"play it 连读，ear 清楚收尾。",example:"A: Should we book now? B: Let's play it by ear.",keys:["play","ear"]},
  {id:"plan-04",group:"约计划",en:"I'll keep you posted.",zh:"我会随时告诉你进展。",scene:"你还没有最终消息，但会更新对方。",tip:"keep you 像 kee-pyou，posted 重一点。",example:"A: Any update? B: I'll keep you posted.",keys:["keep","posted"]},
  {id:"plan-05",group:"约计划",en:"See you then.",zh:"那到时候见。",scene:"时间地点定好后结束对话。",tip:"see you 连读，then 轻落。",example:"A: Monday at nine. B: See you then.",keys:["see","then"]},
  {id:"plan-06",group:"约计划",en:"Can we rain check?",zh:"我们能改天吗？",scene:"临时不方便赴约，礼貌改期。",tip:"rain check 两个词都要清楚。",example:"A: Still on for lunch? B: Can we rain check?",keys:["rain","check"]},
  {id:"plan-07",group:"约计划",en:"Let's grab coffee.",zh:"我们去喝杯咖啡吧。",scene:"轻松约见面，不一定只喝咖啡。",tip:"grab coffee 连起来，coffee 第一音节重。",example:"A: Free this afternoon? B: Let's grab coffee.",keys:["grab","coffee"]},
  {id:"plan-08",group:"约计划",en:"What time works for you?",zh:"你什么时间方便？",scene:"礼貌约时间。",tip:"time 和 works 稍重，for you 弱读。",example:"A: We can meet tomorrow. B: What time works for you?",keys:["time","works"]},
  {id:"plan-09",group:"约计划",en:"I'll be there in ten.",zh:"我十分钟后到。",scene:"告诉对方你快到了。",tip:"there in 可连读，ten 说短。",example:"A: Are you close? B: I'll be there in ten.",keys:["there","ten"]},
  {id:"clarify-01",group:"请求澄清",en:"Could you say that again?",zh:"你能再说一遍吗？",scene:"没听清时，比 What 更礼貌。",tip:"could you 像 could-juh，again 重音在 gain。",example:"A: The code is 4821. B: Could you say that again?",keys:["say","again"]},
  {id:"clarify-02",group:"请求澄清",en:"What do you mean by that?",zh:"你这是什么意思？",scene:"想确认对方具体含义。",tip:"mean by that 连起来，mean 稍重。",example:"A: It's not ready. B: What do you mean by that?",keys:["mean","that"]},
  {id:"clarify-03",group:"请求澄清",en:"Just to be clear.",zh:"我确认一下。",scene:"复述前先铺垫，避免误会。",tip:"just to 像 jus-tu，clear 拉稳。",example:"Just to be clear, we meet at eight, right?",keys:["clear"]},
  {id:"clarify-04",group:"请求澄清",en:"Can you walk me through it?",zh:"你能带我过一遍吗？",scene:"请对方一步步解释流程。",tip:"walk me through 连读，through 不要漏。",example:"Can you walk me through it one more time?",keys:["walk","through"]},
  {id:"clarify-05",group:"请求澄清",en:"Did I get that right?",zh:"我理解对了吗？",scene:"复述后确认自己没误解。",tip:"get that 连读，right 上扬。",example:"You need it by Friday. Did I get that right?",keys:["get","right"]},
  {id:"clarify-06",group:"请求澄清",en:"I missed the last part.",zh:"我没听到最后一部分。",scene:"电话、会议里自然补一句。",tip:"missed the 连读，last part 稍重。",example:"Sorry, I missed the last part.",keys:["missed","last","part"]},
  {id:"clarify-07",group:"请求澄清",en:"How do you pronounce that?",zh:"那个怎么发音？",scene:"遇到名字、单词不会读时。",tip:"pronounce 重音在 nounce。",example:"How do you pronounce that street name?",keys:["pronounce","that"]},
  {id:"clarify-08",group:"请求澄清",en:"What was that called?",zh:"那个叫什么来着？",scene:"想不起某个东西名称时。",tip:"was that 弱读，called 收住 d。",example:"The app you mentioned, what was that called?",keys:["called"]},
  {id:"clarify-09",group:"请求澄清",en:"So you're saying...",zh:"所以你的意思是……",scene:"复述对方观点前自然衔接。",tip:"you're saying 连起来，saying 保持轻。",example:"So you're saying we should wait?",keys:["saying"]},
  {id:"social-01",group:"轻松社交",en:"No worries.",zh:"没事，别担心。",scene:"别人道歉或麻烦你时。",tip:"worries 第一音节重，语气放松。",example:"A: Sorry I'm late. B: No worries.",keys:["worries"]},
  {id:"social-02",group:"轻松社交",en:"You're good.",zh:"没关系，你没事。",scene:"安慰对方不用紧张。",tip:"you're good 连读，good 短促。",example:"A: Did I mess it up? B: You're good.",keys:["good"]},
  {id:"social-03",group:"轻松社交",en:"My bad.",zh:"我的错。",scene:"小失误时轻松道歉。",tip:"bad 是重音，别说得太正式。",example:"A: You sent the old file. B: My bad.",keys:["bad"]},
  {id:"social-04",group:"轻松社交",en:"It's all good.",zh:"都没事。",scene:"化解小尴尬、小问题。",tip:"it's all 连读，good 收短。",example:"A: I forgot to call. B: It's all good.",keys:["all","good"]},
  {id:"social-05",group:"轻松社交",en:"Long time no see.",zh:"好久不见。",scene:"遇到久未见的人。",tip:"time 和 see 稍重，节奏轻松。",example:"Hey, long time no see.",keys:["long","time","see"]},
  {id:"social-06",group:"轻松社交",en:"How's it going?",zh:"最近怎么样？",scene:"比 How are you 更日常。",tip:"how's it 连起来，going 弱收。",example:"Hey Sam, how's it going?",keys:["going"]},
  {id:"social-07",group:"轻松社交",en:"Can't complain.",zh:"还不错，没啥可抱怨。",scene:"回答近况时自然又不夸张。",tip:"can't 和 complain 都要清楚。",example:"A: How are things? B: Can't complain.",keys:["complain"]},
  {id:"social-08",group:"轻松社交",en:"That's wild.",zh:"这也太离谱/厉害了。",scene:"听到惊讶的事时。",tip:"wild 发成 waɪld，d 轻收。",example:"A: He quit and moved to Iceland. B: That's wild.",keys:["wild"]},
  {id:"social-09",group:"轻松社交",en:"Tell me about it.",zh:"可不是嘛，我太懂了。",scene:"强烈认同对方抱怨或感受。",tip:"不是字面让对方解释，about it 连读。",example:"A: Mondays are rough. B: Tell me about it.",keys:["tell","about"]},
  {id:"help-01",group:"帮忙行动",en:"I'm on it.",zh:"我这就去办。",scene:"接下任务时很自然。",tip:"on it 连读，it 轻收。",example:"A: Can you check the file? B: I'm on it.",keys:["on","it"]},
  {id:"help-02",group:"帮忙行动",en:"I can take care of that.",zh:"这个我来处理。",scene:"主动承担一件事。",tip:"take care of 连读，care 稍重。",example:"Don't worry. I can take care of that.",keys:["take","care"]},
  {id:"help-03",group:"帮忙行动",en:"Let me handle it.",zh:"让我来处理。",scene:"你想接手解决问题。",tip:"let me 像 lemme，handle 重音在 han。",example:"The printer is stuck. Let me handle it.",keys:["handle","it"]},
  {id:"help-04",group:"帮忙行动",en:"Give me a sec.",zh:"等我一下。",scene:"需要一点时间时。",tip:"me a 连读，sec 很短。",example:"Give me a sec, I'm opening it now.",keys:["give","sec"]},
  {id:"help-05",group:"帮忙行动",en:"I'll figure it out.",zh:"我会想办法搞定。",scene:"还没答案，但你愿意解决。",tip:"figure it 连读，out 清楚。",example:"I don't know yet, but I'll figure it out.",keys:["figure","out"]},
  {id:"help-06",group:"帮忙行动",en:"I got your back.",zh:"我罩你，我支持你。",scene:"给朋友或同事支持感。",tip:"got your 可连成 gotcher，back 重。",example:"Don't stress. I got your back.",keys:["got","back"]},
  {id:"help-07",group:"帮忙行动",en:"Let me know if you need anything.",zh:"需要什么就告诉我。",scene:"提供帮助但不强迫。",tip:"let me know 连成 lemme know，anything 轻收。",example:"Let me know if you need anything today.",keys:["know","need","anything"]},
  {id:"help-08",group:"帮忙行动",en:"Happy to help.",zh:"很乐意帮忙。",scene:"别人感谢你时自然回应。",tip:"happy 第一音节重，help 收短。",example:"A: Thanks for doing this. B: Happy to help.",keys:["happy","help"]},
  {id:"help-09",group:"帮忙行动",en:"I'll send it over.",zh:"我会发给你。",scene:"发文件、链接、资料时。",tip:"send it 连读，over 平稳下降。",example:"I'll send it over after lunch.",keys:["send","over"]},
  {id:"soften-01",group:"道歉缓和",en:"Sorry about that.",zh:"不好意思，刚才那个抱歉。",scene:"小失误后快速缓和。",tip:"about that 连读，that 轻落。",example:"Sorry about that, I clicked the wrong link.",keys:["sorry","about"]},
  {id:"soften-02",group:"道歉缓和",en:"I didn't mean to.",zh:"我不是故意的。",scene:"解释自己没有恶意。",tip:"didn't mean 连读，mean 稍重。",example:"I didn't mean to interrupt you.",keys:["didn't","mean"]},
  {id:"soften-03",group:"道歉缓和",en:"Thanks for understanding.",zh:"谢谢你理解。",scene:"对方体谅你时。",tip:"thanks for 弱读，understanding 重音在 stand。",example:"I need to reschedule. Thanks for understanding.",keys:["thanks","understanding"]},
  {id:"soften-04",group:"道歉缓和",en:"No big deal.",zh:"没什么大不了。",scene:"让对方别把小事放大。",tip:"big deal 两个词都要清楚。",example:"A: I spilled a little. B: No big deal.",keys:["big","deal"]},
  {id:"soften-05",group:"道歉缓和",en:"It happens.",zh:"这种事难免。",scene:"安慰别人犯小错。",tip:"happens 第一音节重，语气轻。",example:"A: I missed the bus. B: It happens.",keys:["happens"]},
  {id:"soften-06",group:"道歉缓和",en:"I appreciate your patience.",zh:"感谢你耐心等待。",scene:"正式但不僵硬，适合延迟后。",tip:"appreciate 重音在 pre，patience 第一音节重。",example:"I appreciate your patience while I check this.",keys:["appreciate","patience"]},
  {id:"soften-07",group:"道歉缓和",en:"Let's start over.",zh:"我们重新来过吧。",scene:"对话乱了、误会了，重新开始。",tip:"start over 连读，over 轻落。",example:"This got confusing. Let's start over.",keys:["start","over"]},
  {id:"soften-08",group:"道歉缓和",en:"Sorry to keep you waiting.",zh:"抱歉让你久等了。",scene:"迟到、回复慢、处理久了。",tip:"keep you 像 kee-pyou，waiting 第一音节重。",example:"Sorry to keep you waiting. I'm ready now.",keys:["sorry","waiting"]},
  {id:"soften-09",group:"道歉缓和",en:"I should have said that differently.",zh:"我刚才应该换个说法。",scene:"修正自己表达不当。",tip:"should have 可弱读成 should've，differently 重音在 diff。",example:"I should have said that differently. Let me try again.",keys:["should","said","differently"]},
  {id:"opinion-01",group:"表达观点",en:"I feel like...",zh:"我感觉……",scene:"说主观看法，比 I think 更柔和。",tip:"feel like 连读，后面自然接观点。",example:"I feel like we should keep it simple.",keys:["feel","like"]},
  {id:"opinion-02",group:"表达观点",en:"To be honest.",zh:"说实话。",scene:"准备讲真实感受或不同意见。",tip:"to be 弱读，honest 的 h 不发音。",example:"To be honest, I'm not a fan of it.",keys:["honest"]},
  {id:"opinion-03",group:"表达观点",en:"In my experience.",zh:"以我的经验来看。",scene:"分享经验而不是绝对判断。",tip:"experience 重音在 peer。",example:"In my experience, shorter messages work better.",keys:["experience"]},
  {id:"opinion-04",group:"表达观点",en:"I'm not sure about that.",zh:"这个我不太确定。",scene:"委婉表达保留意见。",tip:"not sure about 连起来，that 轻收。",example:"I'm not sure about that deadline.",keys:["sure","about"]},
  {id:"opinion-05",group:"表达观点",en:"That's a good point.",zh:"这个点说得好。",scene:"认可对方观点。",tip:"good point 连读，point 收 t。",example:"That's a good point. We should test it first.",keys:["good","point"]},
  {id:"opinion-06",group:"表达观点",en:"I wouldn't say that.",zh:"我倒不会那么说。",scene:"温和反驳，不直接说你错了。",tip:"wouldn't say 连读，that 短收。",example:"I wouldn't say that. It's more complicated.",keys:["wouldn't","say"]},
  {id:"opinion-07",group:"表达观点",en:"I get where you're coming from.",zh:"我理解你的出发点。",scene:"先共情，再表达不同想法。",tip:"where you're 连读，coming from 稳住节奏。",example:"I get where you're coming from, but I disagree.",keys:["get","coming"]},
  {id:"opinion-08",group:"表达观点",en:"It depends.",zh:"看情况。",scene:"答案不是绝对时。",tip:"depends 重音在 pends。",example:"A: Is it worth it? B: It depends.",keys:["depends"]},
  {id:"opinion-09",group:"表达观点",en:"Here's the thing.",zh:"问题是这样的。",scene:"准备解释关键点。",tip:"here's the 连读，thing 重一点。",example:"Here's the thing: we don't have the budget.",keys:["thing"]},
  {id:"bridge-01",group:"转场接话",en:"By the way.",zh:"顺便说一下。",scene:"自然切到另一个话题。",tip:"by the 弱读，way 稍重。",example:"By the way, did you get my message?",keys:["way"]},
  {id:"bridge-02",group:"转场接话",en:"Speaking of that.",zh:"说到这个。",scene:"接住刚才话题，展开相关内容。",tip:"speaking 重音在 speak，of that 连读。",example:"Speaking of that, I have a quick question.",keys:["speaking","that"]},
  {id:"bridge-03",group:"转场接话",en:"Anyway.",zh:"总之，先这样。",scene:"把话题拉回来或收尾。",tip:"anyway 重音在 way。",example:"Anyway, let's get back to work.",keys:["anyway"]},
  {id:"bridge-04",group:"转场接话",en:"Before I forget.",zh:"趁我还没忘。",scene:"插入一个重要提醒。",tip:"before I 连读，forget 重音在 get。",example:"Before I forget, your package arrived.",keys:["before","forget"]},
  {id:"bridge-05",group:"转场接话",en:"One more thing.",zh:"还有一件事。",scene:"补充最后一点。",tip:"one more 连读，thing 轻收。",example:"One more thing: don't share the link yet.",keys:["one","thing"]},
  {id:"bridge-06",group:"转场接话",en:"That reminds me.",zh:"这倒提醒我了。",scene:"由对方话题联想到另一件事。",tip:"reminds 重音在 minds。",example:"That reminds me, I need to call Alex.",keys:["reminds","me"]},
  {id:"bridge-07",group:"转场接话",en:"Back to what you said.",zh:"回到你刚才说的。",scene:"拉回前面一个观点继续说。",tip:"back to 弱读，said 收短。",example:"Back to what you said, I think you're right.",keys:["back","said"]},
  {id:"bridge-08",group:"转场接话",en:"On a different note.",zh:"换个话题。",scene:"礼貌转到不相关的话题。",tip:"different 第一音节重，note 清楚。",example:"On a different note, how was your trip?",keys:["different","note"]},
  {id:"bridge-09",group:"转场接话",en:"Let's circle back.",zh:"我们回头再说/回到这个点。",scene:"会议或讨论中暂时搁置再回来。",tip:"circle back 节奏清楚，back 重。",example:"Let's circle back after we see the numbers.",keys:["circle","back"]},
  {id:"feeling-01",group:"情绪感受",en:"I'm not feeling it.",zh:"我对这个不太有感觉。",scene:"委婉表达不喜欢某个方案、活动或选择。",tip:"not feeling 连读，feeling 稍重。",example:"I tried the new layout, but I'm not feeling it.",keys:["not","feeling"]},
  {id:"feeling-02",group:"情绪感受",en:"I'm wiped.",zh:"我累瘫了。",scene:"一天很累，想表达精疲力尽。",tip:"wiped 结尾 p/t 收得短，不要拖。",example:"I'm wiped. Let's talk tomorrow.",keys:["wiped"]},
  {id:"feeling-03",group:"情绪感受",en:"I'm a little overwhelmed.",zh:"我有点扛不住了。",scene:"事情太多，需要别人理解你的压力。",tip:"overwhelmed 重音在 whelmed，little 弱读。",example:"I'm a little overwhelmed with everything today.",keys:["little","overwhelmed"]},
  {id:"feeling-04",group:"情绪感受",en:"I'm so relieved.",zh:"我终于松了一口气。",scene:"问题解决、结果出来后。",tip:"relieved 重音在 lieved，尾音 d 轻收。",example:"I'm so relieved the meeting went well.",keys:["so","relieved"]},
  {id:"feeling-05",group:"情绪感受",en:"That made my day.",zh:"这让我一天都开心。",scene:"别人做了让你开心的小事。",tip:"made my 连读，day 拉稳。",example:"You brought coffee? That made my day.",keys:["made","day"]},
  {id:"feeling-06",group:"情绪感受",en:"I'm kind of nervous.",zh:"我有点紧张。",scene:"面试、发言、第一次见面前。",tip:"kind of 可弱读成 kinda，nervous 第一音节重。",example:"I'm kind of nervous about the presentation.",keys:["kind","nervous"]},
  {id:"feeling-07",group:"情绪感受",en:"I can't wait.",zh:"我等不及了，很期待。",scene:"期待旅行、见面、活动。",tip:"can't wait 两个词都短而有力。",example:"I can't wait to see the new place.",keys:["can't","wait"]},
  {id:"feeling-08",group:"情绪感受",en:"I'm not in the mood.",zh:"我现在没这个心情。",scene:"不想做某事，但不想解释太多。",tip:"in the mood 连读，mood 稍重。",example:"I'm not in the mood for a movie tonight.",keys:["mood"]},
  {id:"praise-01",group:"赞美鼓励",en:"You nailed it.",zh:"你做得太好了。",scene:"别人完成任务、表演或回答得很棒。",tip:"nailed it 连读，nailed 是重音。",example:"That pitch was great. You nailed it.",keys:["nailed","it"]},
  {id:"praise-02",group:"赞美鼓励",en:"You got this.",zh:"你可以的。",scene:"给对方打气。",tip:"got this 连起来，this 不要读成 zis。",example:"Take a breath. You got this.",keys:["got","this"]},
  {id:"praise-03",group:"赞美鼓励",en:"That's impressive.",zh:"这很厉害。",scene:"真诚夸成果、经历或能力。",tip:"impressive 重音在 press。",example:"You finished it in one day? That's impressive.",keys:["impressive"]},
  {id:"praise-04",group:"赞美鼓励",en:"Nice one.",zh:"干得漂亮。",scene:"轻松夸一句，朋友同事都能用。",tip:"nice one 连读，one 轻收。",example:"You fixed the bug? Nice one.",keys:["nice","one"]},
  {id:"praise-05",group:"赞美鼓励",en:"I'm proud of you.",zh:"我为你骄傲。",scene:"亲近关系里给强支持。",tip:"proud of 连读，you 轻一点。",example:"You kept going. I'm proud of you.",keys:["proud","you"]},
  {id:"praise-06",group:"赞美鼓励",en:"That's a solid start.",zh:"这是个不错的开始。",scene:"鼓励初稿、第一版、刚起步的成果。",tip:"solid 第一音节重，start 收短。",example:"It needs work, but that's a solid start.",keys:["solid","start"]},
  {id:"praise-07",group:"赞美鼓励",en:"Keep it up.",zh:"继续保持。",scene:"对方做得不错，希望他继续。",tip:"keep it 连读，up 短促。",example:"Your English sounds smoother. Keep it up.",keys:["keep","up"]},
  {id:"praise-08",group:"赞美鼓励",en:"That was smooth.",zh:"刚才很顺。",scene:"夸操作、表达、处理方式很自然。",tip:"smooth 的 th 要轻擦出来。",example:"You handled that call well. That was smooth.",keys:["was","smooth"]},
  {id:"coffee-01",group:"餐厅咖啡",en:"Can I get a latte?",zh:"我可以要一杯拿铁吗？",scene:"点咖啡时最自然的说法之一。",tip:"can I 可连读，latte 重音在 la。",example:"Can I get a latte with oat milk?",keys:["get","latte"]},
  {id:"coffee-02",group:"餐厅咖啡",en:"For here or to go?",zh:"在这儿喝还是带走？",scene:"店员常问的一句话，也要能听懂。",tip:"to go 连读，go 稍重。",example:"A: For here or to go? B: To go, please.",keys:["here","go"]},
  {id:"coffee-03",group:"餐厅咖啡",en:"Could I get that iced?",zh:"这个能做冰的吗？",scene:"点饮料时改成冰的。",tip:"get that iced 连读，iced 收 t。",example:"Could I get that iced, please?",keys:["get","iced"]},
  {id:"coffee-04",group:"餐厅咖啡",en:"No onions, please.",zh:"请不要洋葱。",scene:"点餐时提出忌口或去掉配料。",tip:"onions 第一音节重，please 轻柔。",example:"I'll have the burger, no onions, please.",keys:["no","onions"]},
  {id:"coffee-05",group:"餐厅咖啡",en:"Can we get the check?",zh:"我们可以结账吗？",scene:"餐厅吃完要账单。",tip:"get the 可弱读，check 重。",example:"Can we get the check when you have a second?",keys:["get","check"]},
  {id:"coffee-06",group:"餐厅咖啡",en:"Do you have any recommendations?",zh:"你有什么推荐吗？",scene:"不知道点什么时问店员。",tip:"recommendations 稍长，重音在 da。",example:"Do you have any recommendations for something light?",keys:["have","recommendations"]},
  {id:"coffee-07",group:"餐厅咖啡",en:"I'll have the same.",zh:"我也要一样的。",scene:"跟朋友点同款。",tip:"have the same 连起来，same 重。",example:"That looks good. I'll have the same.",keys:["have","same"]},
  {id:"coffee-08",group:"餐厅咖啡",en:"Could we split the bill?",zh:"我们可以分开付吗？",scene:"和朋友吃饭想 AA。",tip:"split the bill 节奏清楚，bill 重。",example:"Could we split the bill, please?",keys:["split","bill"]},
  {id:"shop-01",group:"购物付款",en:"I'm just browsing.",zh:"我只是随便看看。",scene:"店员来问你是否需要帮助时。",tip:"just browsing 连读，browsing 第一音节重。",example:"Thanks, I'm just browsing.",keys:["just","browsing"]},
  {id:"shop-02",group:"购物付款",en:"Do you have this in another size?",zh:"这个有别的尺码吗？",scene:"试衣服、买鞋时。",tip:"another size 连读，size 重。",example:"Do you have this in another size?",keys:["another","size"]},
  {id:"shop-03",group:"购物付款",en:"Can I try this on?",zh:"我可以试穿这个吗？",scene:"服装店试衣。",tip:"try this on 连读，on 轻收。",example:"Can I try this on in a medium?",keys:["try","on"]},
  {id:"shop-04",group:"购物付款",en:"How much is it?",zh:"这个多少钱？",scene:"询价最常用。",tip:"much is 连读，it 轻。",example:"How much is it with tax?",keys:["much","it"]},
  {id:"shop-05",group:"购物付款",en:"Can I pay by card?",zh:"我可以刷卡吗？",scene:"付款方式确认。",tip:"pay by card 连读，card 重。",example:"Can I pay by card here?",keys:["pay","card"]},
  {id:"shop-06",group:"购物付款",en:"Could I get a receipt?",zh:"可以给我小票吗？",scene:"付款后要收据。",tip:"receipt 的 p 不发音，重音在 ceipt。",example:"Could I get a receipt, please?",keys:["get","receipt"]},
  {id:"shop-07",group:"购物付款",en:"I'll think about it.",zh:"我再考虑一下。",scene:"不想马上买，礼貌离开。",tip:"think about it 连读，think 重。",example:"Thanks. I'll think about it.",keys:["think","about"]},
  {id:"shop-08",group:"购物付款",en:"Is this on sale?",zh:"这个打折吗？",scene:"问优惠。",tip:"on sale 连起来，sale 拉稳。",example:"Is this on sale, or is it full price?",keys:["on","sale"]},
  {id:"travel-01",group:"出行问路",en:"How do I get there?",zh:"我要怎么去那里？",scene:"问路线。",tip:"do I 可连读，there 重。",example:"How do I get there from here?",keys:["get","there"]},
  {id:"travel-02",group:"出行问路",en:"Is it within walking distance?",zh:"走路能到吗？",scene:"判断是否要打车或坐车。",tip:"walking distance 节奏清楚，distance 第一音节重。",example:"Is it within walking distance from the station?",keys:["walking","distance"]},
  {id:"travel-03",group:"出行问路",en:"I'm looking for this address.",zh:"我在找这个地址。",scene:"给别人看地址问路。",tip:"looking for 可弱读，address 重音常在 dress。",example:"Excuse me, I'm looking for this address.",keys:["looking","address"]},
  {id:"travel-04",group:"出行问路",en:"Which way is the subway?",zh:"地铁往哪边走？",scene:"在街上问方向。",tip:"which way 连读，subway 第一音节重。",example:"Which way is the subway?",keys:["way","subway"]},
  {id:"travel-05",group:"出行问路",en:"I think I'm lost.",zh:"我好像迷路了。",scene:"需要别人帮你确认位置。",tip:"think I'm 连读，lost 短促。",example:"I think I'm lost. Is this Market Street?",keys:["think","lost"]},
  {id:"travel-06",group:"出行问路",en:"Could you drop me off here?",zh:"能在这里让我下车吗？",scene:"打车或朋友开车时。",tip:"drop me off 连读，here 稳住。",example:"Could you drop me off here by the corner?",keys:["drop","off","here"]},
  {id:"travel-07",group:"出行问路",en:"How long is the wait?",zh:"要等多久？",scene:"等车、等位、排队时。",tip:"long is 连读，wait 重。",example:"How long is the wait for a table?",keys:["long","wait"]},
  {id:"travel-08",group:"出行问路",en:"Does this bus go downtown?",zh:"这辆公交去市中心吗？",scene:"上车前确认方向。",tip:"bus go 连读，downtown 重音在 down。",example:"Does this bus go downtown?",keys:["bus","downtown"]},
  {id:"message-01",group:"电话消息",en:"Can you hear me?",zh:"你能听到我吗？",scene:"电话、视频会议开头确认声音。",tip:"hear me 连读，me 轻一点。",example:"Can you hear me now?",keys:["hear","me"]},
  {id:"message-02",group:"电话消息",en:"You're breaking up.",zh:"你声音断断续续。",scene:"网络或信号不好时。",tip:"breaking up 连读，break 重。",example:"You're breaking up. Could you repeat that?",keys:["breaking","up"]},
  {id:"message-03",group:"电话消息",en:"I'll call you back.",zh:"我等会儿回你电话。",scene:"现在不方便接电话。",tip:"call you back 连读，back 重。",example:"I'm in a meeting. I'll call you back.",keys:["call","back"]},
  {id:"message-04",group:"电话消息",en:"Shoot me a text.",zh:"给我发条短信。",scene:"让对方文字发来更方便。",tip:"shoot me a 连读，text 短促。",example:"Shoot me a text when you get there.",keys:["shoot","text"]},
  {id:"message-05",group:"电话消息",en:"I just saw your message.",zh:"我刚看到你的消息。",scene:"回复晚了的自然解释。",tip:"just saw 连读，message 第一音节重。",example:"Sorry, I just saw your message.",keys:["saw","message"]},
  {id:"message-06",group:"电话消息",en:"Let me get back to you.",zh:"我晚点回复你。",scene:"需要查一下再答复。",tip:"get back to you 连成一串，back 稍重。",example:"Let me get back to you after I check.",keys:["get","back","you"]},
  {id:"message-07",group:"电话消息",en:"Can you send me the link?",zh:"你能把链接发我吗？",scene:"要链接、文件、地址时。",tip:"send me 连读，link 收 k。",example:"Can you send me the link when you have a chance?",keys:["send","link"]},
  {id:"message-08",group:"电话消息",en:"Sorry, I was on mute.",zh:"不好意思，我刚才静音了。",scene:"视频会议里非常常用。",tip:"on mute 连读，mute 重。",example:"Sorry, I was on mute. I agree with that.",keys:["mute"]},
  {id:"work-01",group:"工作沟通",en:"What's the deadline?",zh:"截止时间是什么时候？",scene:"接任务时先问时间。",tip:"what's the 弱读，deadline 第一音节重。",example:"What's the deadline for this report?",keys:["deadline"]},
  {id:"work-02",group:"工作沟通",en:"I'll take a look.",zh:"我看一下。",scene:"别人发来文件、问题或链接。",tip:"take a look 连读，look 短收。",example:"Send it over and I'll take a look.",keys:["take","look"]},
  {id:"work-03",group:"工作沟通",en:"Can we align on this?",zh:"我们能把这件事对齐一下吗？",scene:"团队讨论目标、范围或口径。",tip:"align 重音在 line，on this 连读。",example:"Before we move on, can we align on this?",keys:["align","this"]},
  {id:"work-04",group:"工作沟通",en:"What's the next step?",zh:"下一步是什么？",scene:"会议或讨论结束前确认行动。",tip:"next step 两个 t/p 收清楚。",example:"What's the next step after this?",keys:["next","step"]},
  {id:"work-05",group:"工作沟通",en:"Let's keep it simple.",zh:"我们把它做简单点。",scene:"方案过复杂时。",tip:"keep it 连读，simple 第一音节重。",example:"Let's keep it simple for the first version.",keys:["keep","simple"]},
  {id:"work-06",group:"工作沟通",en:"I'm blocked on this.",zh:"我卡在这个地方了。",scene:"工作推进不了，需要帮助。",tip:"blocked on this 连读，blocked 重。",example:"I'm blocked on this until I get access.",keys:["blocked","this"]},
  {id:"work-07",group:"工作沟通",en:"Can you give me some context?",zh:"你能给我一点背景吗？",scene:"不清楚来龙去脉时。",tip:"give me 可连成 gimme，context 第一音节重。",example:"Can you give me some context before I jump in?",keys:["context"]},
  {id:"work-08",group:"工作沟通",en:"Let's put a pin in that.",zh:"这个先放一下。",scene:"会议里先搁置一个话题。",tip:"put a pin in that 连读，pin 重。",example:"Let's put a pin in that and come back later.",keys:["put","pin"]},
  {id:"time-01",group:"争取时间",en:"Give me a minute.",zh:"给我一分钟。",scene:"你需要短暂思考或操作。",tip:"give me a 连读，minute 第一音节重。",example:"Give me a minute to pull it up.",keys:["give","minute"]},
  {id:"time-02",group:"争取时间",en:"Let me double-check.",zh:"我再确认一下。",scene:"不想马上给错答案。",tip:"double-check 重音在 double。",example:"Let me double-check the date.",keys:["double","check"]},
  {id:"time-03",group:"争取时间",en:"I'll get back to you shortly.",zh:"我很快回复你。",scene:"比 later 更正式一点。",tip:"shortly 第一音节重，get back 连读。",example:"I'll get back to you shortly with the numbers.",keys:["get","shortly"]},
  {id:"time-04",group:"争取时间",en:"Can I think about it?",zh:"我可以想一下吗？",scene:"别人让你马上决定时。",tip:"think about it 连读，think 重。",example:"Can I think about it and let you know tomorrow?",keys:["think","about"]},
  {id:"time-05",group:"争取时间",en:"I'm still working on it.",zh:"我还在弄。",scene:"对方催进度时。",tip:"working on it 连读，working 第一音节重。",example:"I'm still working on it. I'll send an update soon.",keys:["working","on"]},
  {id:"time-06",group:"争取时间",en:"It's almost done.",zh:"快好了。",scene:"任务接近完成。",tip:"almost done 两个词都清楚。",example:"It's almost done. I just need to review it.",keys:["almost","done"]},
  {id:"time-07",group:"争取时间",en:"I need a bit more time.",zh:"我还需要一点时间。",scene:"请求延期，语气温和。",tip:"bit more 连读，time 重。",example:"I need a bit more time to finish this.",keys:["bit","time"]},
  {id:"time-08",group:"争取时间",en:"I'll let you know by tonight.",zh:"我今晚前告诉你。",scene:"给出具体回复时间。",tip:"let you know 连成 letcha know，tonight 重音在 night。",example:"I'll let you know by tonight.",keys:["know","tonight"]},
  {id:"decide-01",group:"建议决定",en:"It's up to you.",zh:"看你决定。",scene:"把选择权交给对方。",tip:"up to you 连读，you 轻落。",example:"We can eat here or order in. It's up to you.",keys:["up","you"]},
  {id:"decide-02",group:"建议决定",en:"I'm good either way.",zh:"我两种都可以。",scene:"不挑方案时。",tip:"either way 连读，way 重。",example:"Coffee or tea? I'm good either way.",keys:["good","either","way"]},
  {id:"decide-03",group:"建议决定",en:"Let's go with this one.",zh:"就选这个吧。",scene:"做选择、定方案。",tip:"go with this one 连读，one 重。",example:"After comparing them, let's go with this one.",keys:["go","this","one"]},
  {id:"decide-04",group:"建议决定",en:"That might be better.",zh:"那个可能更好。",scene:"委婉提出替代方案。",tip:"might be 连读，better 第一音节重。",example:"If we move it to Friday, that might be better.",keys:["might","better"]},
  {id:"decide-05",group:"建议决定",en:"What do you think?",zh:"你觉得呢？",scene:"征求意见的万能句。",tip:"what do you 可弱读成 whaddaya。",example:"I like the second option. What do you think?",keys:["think"]},
  {id:"decide-06",group:"建议决定",en:"Let's not overthink it.",zh:"别想太复杂了。",scene:"事情够简单，不想过度分析。",tip:"overthink 重音在 think。",example:"It's just dinner. Let's not overthink it.",keys:["overthink"]},
  {id:"decide-07",group:"建议决定",en:"We can always change it later.",zh:"之后还可以改。",scene:"降低决策压力。",tip:"always change it later 节奏平稳，later 重。",example:"Let's pick a date. We can always change it later.",keys:["change","later"]},
  {id:"decide-08",group:"建议决定",en:"Let's sleep on it.",zh:"我们先睡一觉再决定。",scene:"重大决定先别急。",tip:"sleep on it 连读，sleep 重。",example:"It's a big decision. Let's sleep on it.",keys:["sleep","it"]},
  {id:"boundary-01",group:"边界拒绝",en:"I'll pass this time.",zh:"这次我就不去了/不了。",scene:"轻松拒绝邀请。",tip:"pass this time 连读，pass 稍重。",example:"Thanks for inviting me, but I'll pass this time.",keys:["pass","time"]},
  {id:"boundary-02",group:"边界拒绝",en:"That's not really my thing.",zh:"这不太是我的菜。",scene:"不喜欢某活动但不想冒犯。",tip:"really 弱一点，thing 重。",example:"Karaoke sounds fun, but that's not really my thing.",keys:["not","thing"]},
  {id:"boundary-03",group:"边界拒绝",en:"I don't think I can make it.",zh:"我可能去不了。",scene:"拒绝约定或会议。",tip:"think I can 连读，make it 重。",example:"I don't think I can make it tonight.",keys:["make","it"]},
  {id:"boundary-04",group:"边界拒绝",en:"Maybe another time.",zh:"要不下次吧。",scene:"委婉拒绝当下邀请。",tip:"another time 连读，time 重。",example:"I'm pretty tired. Maybe another time.",keys:["another","time"]},
  {id:"boundary-05",group:"边界拒绝",en:"I'm trying to cut back.",zh:"我在尽量少一点。",scene:"拒绝酒、甜食、消费等。",tip:"cut back 两个词都短促。",example:"No dessert for me. I'm trying to cut back.",keys:["cut","back"]},
  {id:"boundary-06",group:"边界拒绝",en:"I'm not comfortable with that.",zh:"这个我不太舒服/不能接受。",scene:"设置边界，表达不愿意。",tip:"comfortable 可读成 comf-ter-ble，with that 连读。",example:"I'm not comfortable with that arrangement.",keys:["comfortable","that"]},
  {id:"boundary-07",group:"边界拒绝",en:"Can we keep it between us?",zh:"这件事能先别外传吗？",scene:"请对方保密。",tip:"keep it between us 连读，between 重。",example:"Can we keep it between us for now?",keys:["keep","between","us"]},
  {id:"boundary-08",group:"边界拒绝",en:"I need some space.",zh:"我需要一点空间。",scene:"情绪或关系中需要独处。",tip:"some space 连读，space 重。",example:"I'm not mad. I just need some space.",keys:["need","space"]},
  {id:"chat-01",group:"熟人闲聊",en:"What's new?",zh:"最近有什么新鲜事？",scene:"熟人见面随口问。",tip:"what's new 连起来，new 轻拉。",example:"Hey, what's new with you?",keys:["new"]},
  {id:"chat-02",group:"熟人闲聊",en:"How have you been?",zh:"你最近怎么样？",scene:"一段时间没见后的寒暄。",tip:"have you 可弱读，been 用短音。",example:"It's been a while. How have you been?",keys:["how","been"]},
  {id:"chat-03",group:"熟人闲聊",en:"Same old, same old.",zh:"老样子。",scene:"回答近况，没有太多变化。",tip:"same old 连读，节奏像一句口头禅。",example:"A: How's work? B: Same old, same old.",keys:["same","old"]},
  {id:"chat-04",group:"熟人闲聊",en:"I was just thinking about you.",zh:"我刚还想到你。",scene:"碰巧遇到或收到消息。",tip:"thinking about you 连读，thinking 重。",example:"I was just thinking about you yesterday.",keys:["thinking","you"]},
  {id:"chat-05",group:"熟人闲聊",en:"We should catch up soon.",zh:"我们改天得好好聊聊。",scene:"久未见面，表达想约。",tip:"catch up soon 连读，catch 重。",example:"We should catch up soon over coffee.",keys:["catch","soon"]},
  {id:"chat-06",group:"熟人闲聊",en:"How did it go?",zh:"结果怎么样？",scene:"问对方面试、考试、会议结果。",tip:"did it 连读，go 上扬。",example:"How did it go with the interview?",keys:["did","go"]},
  {id:"chat-07",group:"熟人闲聊",en:"That's so you.",zh:"这太像你了。",scene:"朋友做了很符合性格的事。",tip:"so you 连读，you 拉一点。",example:"You brought snacks for everyone? That's so you.",keys:["so","you"]},
  {id:"chat-08",group:"熟人闲聊",en:"I owe you one.",zh:"我欠你一次人情。",scene:"别人帮了你。",tip:"owe you one 连读，one 重。",example:"Thanks for covering for me. I owe you one.",keys:["owe","one"]},
  {id:"fix-01",group:"小问题处理",en:"It slipped my mind.",zh:"我一时忘了。",scene:"忘记某事时自然解释。",tip:"slipped my 连读，mind 重。",example:"Sorry, it slipped my mind.",keys:["slipped","mind"]},
  {id:"fix-02",group:"小问题处理",en:"I messed up.",zh:"我搞砸了。",scene:"承认自己出错。",tip:"messed up 连读，up 短促。",example:"I messed up the time. Sorry about that.",keys:["messed","up"]},
  {id:"fix-03",group:"小问题处理",en:"It's not a big deal.",zh:"这不是什么大事。",scene:"安慰别人或淡化问题。",tip:"big deal 重，not a 弱读。",example:"It's not a big deal. We can fix it.",keys:["big","deal"]},
  {id:"fix-04",group:"小问题处理",en:"Let's figure this out.",zh:"我们来把它解决掉。",scene:"遇到问题时进入解决模式。",tip:"figure this out 连读，out 清楚。",example:"Let's figure this out together.",keys:["figure","out"]},
  {id:"fix-05",group:"小问题处理",en:"That's on me.",zh:"这算我的责任。",scene:"主动承担责任。",tip:"on me 连读，me 轻落。",example:"I missed the detail. That's on me.",keys:["on","me"]},
  {id:"fix-06",group:"小问题处理",en:"Can we try that again?",zh:"我们能再试一次吗？",scene:"没成功、没听清、操作错了。",tip:"try that again 连读，again 重音在 gain。",example:"The audio cut out. Can we try that again?",keys:["try","again"]},
  {id:"fix-07",group:"小问题处理",en:"No harm done.",zh:"没造成什么损失。",scene:"事情有惊无险，安慰对方。",tip:"harm done 两个词都稳。",example:"You clicked the wrong button, but no harm done.",keys:["harm","done"]},
  {id:"fix-08",group:"小问题处理",en:"We're good now.",zh:"现在没问题了。",scene:"问题解决后确认状态。",tip:"we're good now 连读，good 重。",example:"I restarted it. We're good now.",keys:["good","now"]},
  {id:"agree-01",group:"同意不同意",en:"Totally.",zh:"完全同意。",scene:"很自然地强烈认同。",tip:"to-tal-ly 三拍，第一音节重。",example:"A: This place is cozy. B: Totally.",keys:["totally"]},
  {id:"agree-02",group:"同意不同意",en:"Exactly.",zh:"正是这样。",scene:"对方说中你的意思。",tip:"exactly 重音在 xact。",example:"A: It's more about timing. B: Exactly.",keys:["exactly"]},
  {id:"agree-03",group:"同意不同意",en:"Not exactly.",zh:"不完全是。",scene:"温和纠正对方。",tip:"not exact 连读，exactly 重音在 xact。",example:"A: So you quit? B: Not exactly.",keys:["not","exactly"]},
  {id:"agree-04",group:"同意不同意",en:"I see your point.",zh:"我明白你的点。",scene:"先认可对方，再继续补充。",tip:"see your 可连读，point 收 t。",example:"I see your point, but I still have concerns.",keys:["see","point"]},
  {id:"agree-05",group:"同意不同意",en:"You're not wrong.",zh:"你说得也不是没道理。",scene:"半同意，语气常带一点保留。",tip:"not wrong 两个词都清楚。",example:"You're not wrong. We should be careful.",keys:["not","wrong"]},
  {id:"agree-06",group:"同意不同意",en:"I wouldn't put it that way.",zh:"我不会那样说。",scene:"不直接否定，但换一种说法。",tip:"put it that way 连读，way 重。",example:"I wouldn't put it that way, but I get it.",keys:["put","way"]},
  {id:"agree-07",group:"同意不同意",en:"That's true.",zh:"这倒是真的。",scene:"承认一个事实或观点。",tip:"that's true 连读，true 拉稳。",example:"That's true. We do need more time.",keys:["true"]},
  {id:"agree-08",group:"同意不同意",en:"I guess so.",zh:"应该是吧。",scene:"不太确定地同意。",tip:"guess so 连读，so 轻落。",example:"A: Are we done? B: I guess so.",keys:["guess","so"]},
  {id:"degree-01",group:"语气程度",en:"Pretty much.",zh:"差不多，基本上。",scene:"回答是否完成、是否正确。",tip:"pretty 可弱读，much 重。",example:"A: Are you ready? B: Pretty much.",keys:["pretty","much"]},
  {id:"degree-02",group:"语气程度",en:"Kind of.",zh:"有点，算是吧。",scene:"不想说得太绝对。",tip:"kind of 常说成 kinda。",example:"A: Do you like it? B: Kind of.",keys:["kind"]},
  {id:"degree-03",group:"语气程度",en:"More or less.",zh:"差不多，大体上。",scene:"表达不是百分百但基本成立。",tip:"more or less 连读，less 重。",example:"The setup is more or less done.",keys:["more","less"]},
  {id:"degree-04",group:"语气程度",en:"Not really.",zh:"不太是，不怎么。",scene:"委婉否定。",tip:"not really 连读，really 第一音节重。",example:"A: Are you hungry? B: Not really.",keys:["not","really"]},
  {id:"degree-05",group:"语气程度",en:"For sure.",zh:"肯定，当然。",scene:"强确认，比 yes 更口语。",tip:"for sure 连读，sure 拉稳。",example:"A: Can you help? B: For sure.",keys:["sure"]},
  {id:"degree-06",group:"语气程度",en:"No doubt.",zh:"毫无疑问。",scene:"非常确定。",tip:"doubt 的 b 不发音。",example:"No doubt, this is the better option.",keys:["doubt"]},
  {id:"degree-07",group:"语气程度",en:"Big time.",zh:"非常，特别。",scene:"加强语气，常放句尾。",tip:"big time 两个词都短而有力。",example:"A: Was it expensive? B: Big time.",keys:["big","time"]},
  {id:"degree-08",group:"语气程度",en:"At least.",zh:"至少嘛。",scene:"从坏情况里找一点好处。",tip:"at least 连读，least 收 t。",example:"At least we learned something.",keys:["least"]},
  {id:"home-01",group:"家里生活",en:"I'll be right back.",zh:"我马上回来。",scene:"临时离开一下。",tip:"right back 两个词连得紧，back 重。",example:"I'll be right back. Don't start without me.",keys:["right","back"]},
  {id:"home-02",group:"家里生活",en:"Be right there.",zh:"马上来。",scene:"别人叫你，你回应一下。",tip:"省略 I'll，right there 连读。",example:"A: Dinner's ready. B: Be right there.",keys:["right","there"]},
  {id:"home-03",group:"家里生活",en:"Leave it there.",zh:"放那儿就行。",scene:"告诉别人东西放哪里。",tip:"leave it there 连读，there 重。",example:"Leave it there on the table.",keys:["leave","there"]},
  {id:"home-04",group:"家里生活",en:"It's in the fridge.",zh:"在冰箱里。",scene:"回答食物饮料在哪里。",tip:"in the fridge 连读，fridge 收 dge。",example:"The milk? It's in the fridge.",keys:["fridge"]},
  {id:"home-05",group:"家里生活",en:"I'm heading out.",zh:"我要出门了。",scene:"离家或离开某处前。",tip:"heading out 连读，out 清楚。",example:"I'm heading out. See you tonight.",keys:["heading","out"]},
  {id:"home-06",group:"家里生活",en:"Can you grab my keys?",zh:"你能帮我拿一下钥匙吗？",scene:"请家人朋友顺手拿东西。",tip:"grab my keys 连读，keys 重。",example:"Can you grab my keys by the door?",keys:["grab","keys"]},
  {id:"home-07",group:"家里生活",en:"The place is a mess.",zh:"这里乱成一团。",scene:"形容房间或现场很乱。",tip:"place is 可连读，mess 重。",example:"Sorry, the place is a mess.",keys:["place","mess"]},
  {id:"home-08",group:"家里生活",en:"Make yourself at home.",zh:"别拘束，当自己家。",scene:"招待客人时。",tip:"yourself at home 连读，home 重。",example:"Come in. Make yourself at home.",keys:["yourself","home"]},
  {id:"health-01",group:"健康状态",en:"I'm not feeling well.",zh:"我不太舒服。",scene:"身体不舒服的万能句。",tip:"feeling well 连读，well 重。",example:"I'm not feeling well, so I'll stay home.",keys:["feeling","well"]},
  {id:"health-02",group:"健康状态",en:"I have a sore throat.",zh:"我嗓子疼。",scene:"感冒或喉咙不舒服。",tip:"sore throat 两个 th/ r 要清楚。",example:"I have a sore throat and a cough.",keys:["sore","throat"]},
  {id:"health-03",group:"健康状态",en:"I feel a little dizzy.",zh:"我有点头晕。",scene:"身体不适或低血糖。",tip:"feel a little 连读，dizzy 第一音节重。",example:"I feel a little dizzy. Can I sit down?",keys:["feel","dizzy"]},
  {id:"health-04",group:"健康状态",en:"I need to lie down.",zh:"我需要躺一下。",scene:"累、头晕或不舒服。",tip:"need to 可弱读，lie down 连读。",example:"I need to lie down for a bit.",keys:["lie","down"]},
  {id:"health-05",group:"健康状态",en:"I'm coming down with something.",zh:"我好像要生病了。",scene:"感觉感冒快来了。",tip:"coming down with 连成一串，something 弱读。",example:"I think I'm coming down with something.",keys:["coming","down","something"]},
  {id:"health-06",group:"健康状态",en:"I'm feeling much better.",zh:"我感觉好多了。",scene:"病后恢复。",tip:"much better 连读，better 第一音节重。",example:"Thanks for checking in. I'm feeling much better.",keys:["much","better"]},
  {id:"health-07",group:"健康状态",en:"I need some fresh air.",zh:"我需要透透气。",scene:"闷、紧张或不舒服时。",tip:"fresh air 连读，air 拉稳。",example:"I need some fresh air. I'll step outside.",keys:["fresh","air"]},
  {id:"health-08",group:"健康状态",en:"Take care of yourself.",zh:"照顾好自己。",scene:"关心别人身体或状态。",tip:"care of yourself 连读，yourself 重。",example:"Get some rest and take care of yourself.",keys:["care","yourself"]},
  {id:"tech-01",group:"网络科技",en:"My phone died.",zh:"我手机没电关机了。",scene:"解释失联或没回复。",tip:"phone died 连读，died 拉稳。",example:"Sorry I missed your call. My phone died.",keys:["phone","died"]},
  {id:"tech-02",group:"网络科技",en:"The Wi-Fi is spotty.",zh:"Wi-Fi 信号不稳定。",scene:"网断断续续。",tip:"spotty 第一音节重，t 轻弹。",example:"The Wi-Fi is spotty, so I might drop.",keys:["wifi","spotty"]},
  {id:"tech-03",group:"网络科技",en:"It won't load.",zh:"它加载不出来。",scene:"网页、图片、App 打不开。",tip:"won't load 两个词都清楚。",example:"The page won't load on my phone.",keys:["won't","load"]},
  {id:"tech-04",group:"网络科技",en:"Can you refresh it?",zh:"你能刷新一下吗？",scene:"网页或数据没有更新。",tip:"refresh 重音在 fresh，it 轻收。",example:"Can you refresh it and try again?",keys:["refresh","it"]},
  {id:"tech-05",group:"网络科技",en:"I got kicked out.",zh:"我被踢出来了/掉线了。",scene:"会议、群聊、系统突然退出。",tip:"kicked out 连读，out 清楚。",example:"I got kicked out of the meeting.",keys:["kicked","out"]},
  {id:"tech-06",group:"网络科技",en:"The app keeps crashing.",zh:"这个 App 一直闪退。",scene:"描述软件问题。",tip:"keeps crashing 节奏清楚，crashing 第一音节重。",example:"The app keeps crashing when I open it.",keys:["app","crashing"]},
  {id:"tech-07",group:"网络科技",en:"Can you share your screen?",zh:"你能共享屏幕吗？",scene:"视频会议协作。",tip:"share your screen 连读，screen 重。",example:"Can you share your screen for a second?",keys:["share","screen"]},
  {id:"tech-08",group:"网络科技",en:"I can't log in.",zh:"我登录不了。",scene:"账号或系统进不去。",tip:"log in 连读，in 轻收。",example:"I can't log in with my password.",keys:["log","in"]},
  {id:"money-01",group:"金钱账单",en:"It's on me.",zh:"这顿我请。",scene:"请客付款时。",tip:"on me 连读，me 重一点。",example:"Don't worry about it. It's on me.",keys:["on","me"]},
  {id:"money-02",group:"金钱账单",en:"Let's split it.",zh:"我们分摊吧。",scene:"AA 付款。",tip:"split it 连读，it 短。",example:"Let's split it down the middle.",keys:["split","it"]},
  {id:"money-03",group:"金钱账单",en:"Can you cover me?",zh:"你能先帮我垫一下吗？",scene:"暂时没法付款。",tip:"cover me 连读，cover 第一音节重。",example:"I forgot my wallet. Can you cover me?",keys:["cover","me"]},
  {id:"money-04",group:"金钱账单",en:"I'll pay you back.",zh:"我会还你的。",scene:"别人垫钱后。",tip:"pay you back 连读，back 重。",example:"Thanks. I'll pay you back tonight.",keys:["pay","back"]},
  {id:"money-05",group:"金钱账单",en:"Keep the change.",zh:"不用找了。",scene:"小费或零钱不需要找。",tip:"keep the change 连读，change 重。",example:"Thanks, keep the change.",keys:["keep","change"]},
  {id:"money-06",group:"金钱账单",en:"That seems pricey.",zh:"这个好像有点贵。",scene:"委婉说价格高。",tip:"seems pricey 连读，pricey 第一音节重。",example:"That seems pricey for such a small room.",keys:["seems","pricey"]},
  {id:"money-07",group:"金钱账单",en:"Is tip included?",zh:"小费包含了吗？",scene:"餐厅或服务账单确认。",tip:"tip included 连读，included 重音在 clu。",example:"Is tip included in the bill?",keys:["tip","included"]},
  {id:"money-08",group:"金钱账单",en:"Can I get a refund?",zh:"我可以退款吗？",scene:"退货或服务没用上。",tip:"refund 名词常第一音节重。",example:"This doesn't work. Can I get a refund?",keys:["get","refund"]},
  {id:"surprise-01",group:"惊讶反应",en:"No way.",zh:"不会吧。",scene:"惊讶、不敢相信。",tip:"no way 两个词都拉一点。",example:"A: She won again. B: No way.",keys:["no","way"]},
  {id:"surprise-02",group:"惊讶反应",en:"Are you serious?",zh:"你认真的吗？",scene:"震惊或确认真假。",tip:"serious 第一音节重，语气上扬。",example:"You met him in person? Are you serious?",keys:["serious"]},
  {id:"surprise-03",group:"惊讶反应",en:"You're kidding.",zh:"你开玩笑吧。",scene:"听到意外消息。",tip:"kidding 第一音节重，语气可上扬。",example:"A: The flight got canceled. B: You're kidding.",keys:["kidding"]},
  {id:"surprise-04",group:"惊讶反应",en:"That's crazy.",zh:"这也太夸张了。",scene:"惊讶、觉得离谱。",tip:"crazy 第一音节重。",example:"You waited three hours? That's crazy.",keys:["crazy"]},
  {id:"surprise-05",group:"惊讶反应",en:"I didn't see that coming.",zh:"我没想到会这样。",scene:"结果出乎意料。",tip:"see that coming 连读，coming 第一音节重。",example:"I didn't see that coming at all.",keys:["see","coming"]},
  {id:"surprise-06",group:"惊讶反应",en:"What are the odds?",zh:"这也太巧了吧。",scene:"偶然巧合。",tip:"what are 可弱读，odds 收 dz。",example:"We booked the same hotel? What are the odds?",keys:["odds"]},
  {id:"surprise-07",group:"惊讶反应",en:"That's insane.",zh:"这太惊人/离谱了。",scene:"比 crazy 更强烈。",tip:"insane 重音在 sane。",example:"You ran a marathon with no training? That's insane.",keys:["insane"]},
  {id:"surprise-08",group:"惊讶反应",en:"I can't believe it.",zh:"我简直不敢相信。",scene:"强烈惊讶或开心。",tip:"can't believe it 连读，believe 重。",example:"I can't believe it. We actually did it.",keys:["believe","it"]},
  {id:"bye-01",group:"结束对话",en:"I gotta run.",zh:"我得走了。",scene:"需要结束聊天或离开。",tip:"gotta run 一口气说，run 重。",example:"This was fun, but I gotta run.",keys:["gotta","run"]},
  {id:"bye-02",group:"结束对话",en:"Talk soon.",zh:"回头聊。",scene:"轻松结束消息或电话。",tip:"talk soon 两个词都短。",example:"Thanks for the update. Talk soon.",keys:["talk","soon"]},
  {id:"bye-03",group:"结束对话",en:"Catch you later.",zh:"回头见。",scene:"朋友之间告别。",tip:"catch you 可连成 catcha，later 重。",example:"I have class now. Catch you later.",keys:["catch","later"]},
  {id:"bye-04",group:"结束对话",en:"Have a good one.",zh:"祝你今天愉快。",scene:"店员、同事、陌生人之间都常用。",tip:"good one 连读，one 轻收。",example:"Thanks for stopping by. Have a good one.",keys:["good","one"]},
  {id:"bye-05",group:"结束对话",en:"I'll let you go.",zh:"那我不打扰你了。",scene:"电话或聊天礼貌收尾。",tip:"let you go 连读，go 轻落。",example:"I know you're busy, so I'll let you go.",keys:["let","go"]},
  {id:"bye-06",group:"结束对话",en:"Let's wrap this up.",zh:"我们收个尾吧。",scene:"会议、讨论快结束。",tip:"wrap this up 连读，wrap 重。",example:"We're almost out of time. Let's wrap this up.",keys:["wrap","up"]},
  {id:"bye-07",group:"结束对话",en:"Thanks for your time.",zh:"谢谢你的时间。",scene:"会议、面试、咨询结束。",tip:"thanks for 可弱读，time 重。",example:"Thanks for your time. This was helpful.",keys:["thanks","time"]},
  {id:"bye-08",group:"结束对话",en:"I'll see myself out.",zh:"我自己出去就行。",scene:"离开别人家或办公室时。",tip:"see myself out 连读，out 清楚。",example:"No need to walk me. I'll see myself out.",keys:["see","out"]},
  {id:"support-01",group:"安慰支持",en:"I'm here for you.",zh:"我会陪着你/支持你。",scene:"朋友难过时给支持。",tip:"here for you 连读，you 轻柔。",example:"I'm here for you if you want to talk.",keys:["here","you"]},
  {id:"support-02",group:"安慰支持",en:"Take your time.",zh:"慢慢来，不着急。",scene:"对方需要时间、情绪或操作。",tip:"take your time 连读，time 重。",example:"Take your time. There's no rush.",keys:["take","time"]},
  {id:"support-03",group:"安慰支持",en:"No pressure.",zh:"别有压力。",scene:"给对方选择空间。",tip:"pressure 第一音节重。",example:"Join us if you want, but no pressure.",keys:["no","pressure"]},
  {id:"support-04",group:"安慰支持",en:"You've got this.",zh:"你能行的。",scene:"鼓励别人面对挑战。",tip:"you've got this 连读，got 重。",example:"You've prepared a lot. You've got this.",keys:["got","this"]},
  {id:"support-05",group:"安慰支持",en:"That sounds rough.",zh:"听起来挺难受/挺糟的。",scene:"共情别人遇到麻烦。",tip:"sounds rough 连读，rough 重。",example:"You had to redo everything? That sounds rough.",keys:["sounds","rough"]},
  {id:"support-06",group:"安慰支持",en:"Don't beat yourself up.",zh:"别太责怪自己。",scene:"别人自责时。",tip:"beat yourself up 连读，up 短。",example:"It was an honest mistake. Don't beat yourself up.",keys:["beat","yourself","up"]},
  {id:"support-07",group:"安慰支持",en:"It's okay to take a break.",zh:"休息一下也没关系。",scene:"对方累了、压力大。",tip:"take a break 连读，break 重。",example:"You've been working all day. It's okay to take a break.",keys:["take","break"]},
  {id:"support-08",group:"安慰支持",en:"I'm rooting for you.",zh:"我支持你/给你加油。",scene:"鼓励朋友做挑战。",tip:"rooting for you 连读，rooting 第一音节重。",example:"Good luck tomorrow. I'm rooting for you.",keys:["rooting","you"]},
  {id:"urgent-01",group:"临场救急",en:"Could you slow down?",zh:"你能说慢一点吗？",scene:"对方语速太快时。",tip:"slow down 连读，down 重。",example:"Sorry, could you slow down a little?",keys:["slow","down"]},
  {id:"urgent-02",group:"临场救急",en:"I don't follow.",zh:"我没跟上。",scene:"没理解对方逻辑。",tip:"don't follow 连读，follow 第一音节重。",example:"I don't follow. Can you explain it again?",keys:["follow"]},
  {id:"urgent-03",group:"临场救急",en:"I'm new here.",zh:"我刚来/我不熟这里。",scene:"到新地方、新团队时。",tip:"new here 连读，here 稳住。",example:"I'm new here. Could you point me to reception?",keys:["new","here"]},
  {id:"urgent-04",group:"临场救急",en:"Could you write it down?",zh:"你能写下来吗？",scene:"听不清名字、地址、号码。",tip:"write it down 连读，down 重。",example:"Could you write it down for me?",keys:["write","down"]},
  {id:"urgent-05",group:"临场救急",en:"I only speak a little English.",zh:"我只会说一点英语。",scene:"需要对方放慢或简单说。",tip:"only speak a little 连读，English 重。",example:"I only speak a little English. Could you speak slowly?",keys:["speak","little","english"]},
  {id:"urgent-06",group:"临场救急",en:"Can you show me?",zh:"你能给我看一下吗？",scene:"听不懂时改用示范。",tip:"show me 连读，show 重。",example:"I'm not sure how to do it. Can you show me?",keys:["show","me"]},
  {id:"urgent-07",group:"临场救急",en:"I need help with this.",zh:"这个我需要帮忙。",scene:"明确求助。",tip:"help with this 连读，help 重。",example:"I need help with this form.",keys:["help","this"]},
  {id:"urgent-08",group:"临场救急",en:"Is there another way?",zh:"还有别的办法吗？",scene:"当前方法行不通时。",tip:"another way 连读，way 重。",example:"This card isn't working. Is there another way?",keys:["another","way"]}
];
