window.SPEAK_DAILY_GROUPS = ["理解回应", "约计划", "请求澄清", "轻松社交", "帮忙行动", "道歉缓和", "表达观点", "转场接话"];

window.SPEAK_DAILY_PHRASES = [
  {id:"understand-01",group:"理解回应",en:"I got it.",zh:"我明白了。",scene:"别人交代任务、规则或安排时。",tip:"I got 连起来，重音落在 got，it 轻轻收尾。",example:"A: Send this before noon. B: I got it.",keys:["got","it"]},
  {id:"understand-02",group:"理解回应",en:"Gotcha.",zh:"懂了，收到。",scene:"熟人之间快速回应，比 I understand 更口语。",tip:"像 got-chuh，一口气说完，不要拖长。",example:"A: Turn left after the bank. B: Gotcha.",keys:["gotcha"]},
  {id:"understand-03",group:"理解回应",en:"Makes sense.",zh:"说得通，有道理。",scene:"别人解释原因后，你表示理解。",tip:"重音在 sense，makes 可以弱读。",example:"A: Traffic was terrible. B: Makes sense.",keys:["makes","sense"]},
  {id:"understand-04",group:"理解回应",en:"Fair enough.",zh:"也行，可以理解。",scene:"你不完全同意，但接受对方理由。",tip:"fair enough 连读，enough 的 n 要清楚。",example:"A: I need more time. B: Fair enough.",keys:["fair","enough"]},
  {id:"understand-05",group:"理解回应",en:"I see what you mean.",zh:"我懂你的意思。",scene:"对方表达观点后，你表示跟上了。",tip:"see 和 mean 稍重，中间保持轻快。",example:"A: It feels too formal. B: I see what you mean.",keys:["see","mean"]},
  {id:"understand-06",group:"理解回应",en:"That works for me.",zh:"这个对我可以。",scene:"确认时间、方案、安排都可用。",tip:"works 是核心重音，for me 轻一点。",example:"A: How about Friday? B: That works for me.",keys:["works","me"]},
  {id:"understand-07",group:"理解回应",en:"I'm with you.",zh:"我跟得上，我同意。",scene:"会议、聊天中表示理解或站在同一边。",tip:"I'm with 连起来，with 的 th 不要吞掉。",example:"A: We should keep it simple. B: I'm with you.",keys:["with","you"]},
  {id:"understand-08",group:"理解回应",en:"Good to know.",zh:"知道了，挺有用。",scene:"别人补充一个实用信息时。",tip:"good to 像 good-du，know 收住。",example:"A: They close at six. B: Good to know.",keys:["good","know"]},
  {id:"understand-09",group:"理解回应",en:"That explains it.",zh:"这就解释得通了。",scene:"听到原因后，一下子明白情况。",tip:"explains 是主重音，it 很轻。",example:"A: The train was delayed. B: That explains it.",keys:["explains","it"]},
  {id:"plan-01",group:"约计划",en:"Sounds good.",zh:"听起来不错，就这么定。",scene:"答应建议、确认安排时。",tip:"sounds 的 z 音带出来，good 短促。",example:"A: Let's meet at two. B: Sounds good.",keys:["sounds","good"]},
  {id:"plan-02",group:"约计划",en:"I'm down.",zh:"我可以，我愿意。",scene:"朋友邀请你参加活动时。",tip:"down 是重音，语气轻松。",example:"A: Want to grab dinner? B: I'm down.",keys:["down"]},
  {id:"plan-03",group:"约计划",en:"Let's play it by ear.",zh:"到时候看情况吧。",scene:"计划未定，先保持灵活。",tip:"play it 连读，ear 清楚收尾。",example:"A: Should we book now? B: Let's play it by ear.",keys:["play","ear"]},
  {id:"plan-04",group:"约计划",en:"I'll keep you posted.",zh:"我会随时告诉你进展。",scene:"你还没有最终消息，但会更新对方。",tip:"keep you 像 kee-pyou，posted 重一点。",example:"A: Any update? B: I'll keep you posted.",keys:["keep","posted"]},
  {id:"plan-05",group:"约计划",en:"See you then.",zh:"那到时候见。",scene:"时间地点定好后结束对话。",tip:"see you 连读，then 轻落。",example:"A: Monday at nine. B: See you then.",keys:["see","then"]},
  {id:"plan-06",group:"约计划",en:"Can we rain check?",zh:"我们能改天吗？",scene:"临时不方便赴约，礼貌改期。",tip:"rain check 两个词都要清楚。",example:"A: Still on for lunch? B: Can we rain check?",keys:["rain","check"]},
  {id:"plan-07",group:"约计划",en:"Let's grab coffee.",zh:"我们去喝杯咖啡吧。",scene:"轻松约见面，不一定只喝咖啡。",tip:"grab coffee 连起来，coffee 第一音节重。",example:"A: Free this afternoon? B: Let's grab coffee.",keys:["grab","coffee"]},
  {id:"plan-08",group:"约计划",en:"What time works for you?",zh:"你什么时间方便？",scene:"礼貌约时间。",tip:"time 和 works 稍重，for you 弱读。",example:"A: We can meet tomorrow. B: What time works for you?",keys:["time","works"]},
  {id:"plan-09",group:"约计划",en:"I'll be there in ten.",zh:"我十分钟后到。",scene:"告诉对方你快到了。",tip:"there in 可连读，ten 说短。",example:"A: Are you close? B: I'll be there in ten.",keys:["there","ten"]},
  {id:"clarify-01",group:"请求澄清",en:"Could you say that again?",zh:"你能再说一遍吗？",scene:"没听清时，比 What 更礼貌。",tip:"could you 像 could-juh，again 重音在 gain。",example:"A: The code is 4821. B: Could you say that again?",keys:["say","again"]},
  {id:"clarify-02",group:"请求澄清",en:"What do you mean by that?",zh:"你这是什么意思？",scene:"想确认对方具体含义。",tip:"mean by that 连起来，mean 稍重。",example:"A: It's not ready. B: What do you mean by that?",keys:["mean","that"]},
  {id:"clarify-03",group:"请求澄清",en:"Just to be clear.",zh:"我确认一下。",scene:"复述前先铺垫，避免误会。",tip:"just to 像 jus-tu，clear 拉稳。",example:"Just to be clear, we meet at eight, right?",keys:["clear"]},
  {id:"clarify-04",group:"请求澄清",en:"Can you walk me through it?",zh:"你能带我过一遍吗？",scene:"请对方一步步解释流程。",tip:"walk me through 连读，through 不要漏。",example:"Can you walk me through it one more time?",keys:["walk","through"]},
  {id:"clarify-05",group:"请求澄清",en:"Did I get that right?",zh:"我理解对了吗？",scene:"复述后确认自己没误解。",tip:"get that 连读，right 上扬。",example:"You need it by Friday. Did I get that right?",keys:["get","right"]},
  {id:"clarify-06",group:"请求澄清",en:"I missed the last part.",zh:"我没听到最后一部分。",scene:"电话、会议里自然补一句。",tip:"missed the 连读，last part 稍重。",example:"Sorry, I missed the last part.",keys:["missed","last","part"]},
  {id:"clarify-07",group:"请求澄清",en:"How do you pronounce that?",zh:"那个怎么发音？",scene:"遇到名字、单词不会读时。",tip:"pronounce 重音在 nounce。",example:"How do you pronounce that street name?",keys:["pronounce","that"]},
  {id:"clarify-08",group:"请求澄清",en:"What was that called?",zh:"那个叫什么来着？",scene:"想不起某个东西名称时。",tip:"was that 弱读，called 收住 d。",example:"The app you mentioned, what was that called?",keys:["called"]},
  {id:"clarify-09",group:"请求澄清",en:"So you're saying...",zh:"所以你的意思是……",scene:"复述对方观点前自然衔接。",tip:"you're saying 连起来，saying 保持轻。",example:"So you're saying we should wait?",keys:["saying"]},
  {id:"social-01",group:"轻松社交",en:"No worries.",zh:"没事，别担心。",scene:"别人道歉或麻烦你时。",tip:"worries 第一音节重，语气放松。",example:"A: Sorry I'm late. B: No worries.",keys:["worries"]},
  {id:"social-02",group:"轻松社交",en:"You're good.",zh:"没关系，你没事。",scene:"安慰对方不用紧张。",tip:"you're good 连读，good 短促。",example:"A: Did I mess it up? B: You're good.",keys:["good"]},
  {id:"social-03",group:"轻松社交",en:"My bad.",zh:"我的错。",scene:"小失误时轻松道歉。",tip:"bad 是重音，别说得太正式。",example:"A: You sent the old file. B: My bad.",keys:["bad"]},
  {id:"social-04",group:"轻松社交",en:"It's all good.",zh:"都没事。",scene:"化解小尴尬、小问题。",tip:"it's all 连读，good 收短。",example:"A: I forgot to call. B: It's all good.",keys:["all","good"]},
  {id:"social-05",group:"轻松社交",en:"Long time no see.",zh:"好久不见。",scene:"遇到久未见的人。",tip:"time 和 see 稍重，节奏轻松。",example:"Hey, long time no see.",keys:["long","time","see"]},
  {id:"social-06",group:"轻松社交",en:"How's it going?",zh:"最近怎么样？",scene:"比 How are you 更日常。",tip:"how's it 连起来，going 弱收。",example:"Hey Sam, how's it going?",keys:["going"]},
  {id:"social-07",group:"轻松社交",en:"Can't complain.",zh:"还不错，没啥可抱怨。",scene:"回答近况时自然又不夸张。",tip:"can't 和 complain 都要清楚。",example:"A: How are things? B: Can't complain.",keys:["complain"]},
  {id:"social-08",group:"轻松社交",en:"That's wild.",zh:"这也太离谱/厉害了。",scene:"听到惊讶的事时。",tip:"wild 发成 waɪld，d 轻收。",example:"A: He quit and moved to Iceland. B: That's wild.",keys:["wild"]},
  {id:"social-09",group:"轻松社交",en:"Tell me about it.",zh:"可不是嘛，我太懂了。",scene:"强烈认同对方抱怨或感受。",tip:"不是字面让对方解释，about it 连读。",example:"A: Mondays are rough. B: Tell me about it.",keys:["tell","about"]},
  {id:"help-01",group:"帮忙行动",en:"I'm on it.",zh:"我这就去办。",scene:"接下任务时很自然。",tip:"on it 连读，it 轻收。",example:"A: Can you check the file? B: I'm on it.",keys:["on","it"]},
  {id:"help-02",group:"帮忙行动",en:"I can take care of that.",zh:"这个我来处理。",scene:"主动承担一件事。",tip:"take care of 连读，care 稍重。",example:"Don't worry. I can take care of that.",keys:["take","care"]},
  {id:"help-03",group:"帮忙行动",en:"Let me handle it.",zh:"让我来处理。",scene:"你想接手解决问题。",tip:"let me 像 lemme，handle 重音在 han。",example:"The printer is stuck. Let me handle it.",keys:["handle","it"]},
  {id:"help-04",group:"帮忙行动",en:"Give me a sec.",zh:"等我一下。",scene:"需要一点时间时。",tip:"me a 连读，sec 很短。",example:"Give me a sec, I'm opening it now.",keys:["give","sec"]},
  {id:"help-05",group:"帮忙行动",en:"I'll figure it out.",zh:"我会想办法搞定。",scene:"还没答案，但你愿意解决。",tip:"figure it 连读，out 清楚。",example:"I don't know yet, but I'll figure it out.",keys:["figure","out"]},
  {id:"help-06",group:"帮忙行动",en:"I got your back.",zh:"我罩你，我支持你。",scene:"给朋友或同事支持感。",tip:"got your 可连成 gotcher，back 重。",example:"Don't stress. I got your back.",keys:["got","back"]},
  {id:"help-07",group:"帮忙行动",en:"Let me know if you need anything.",zh:"需要什么就告诉我。",scene:"提供帮助但不强迫。",tip:"let me know 连成 lemme know，anything 轻收。",example:"Let me know if you need anything today.",keys:["know","need","anything"]},
  {id:"help-08",group:"帮忙行动",en:"Happy to help.",zh:"很乐意帮忙。",scene:"别人感谢你时自然回应。",tip:"happy 第一音节重，help 收短。",example:"A: Thanks for doing this. B: Happy to help.",keys:["happy","help"]},
  {id:"help-09",group:"帮忙行动",en:"I'll send it over.",zh:"我会发给你。",scene:"发文件、链接、资料时。",tip:"send it 连读，over 平稳下降。",example:"I'll send it over after lunch.",keys:["send","over"]},
  {id:"soften-01",group:"道歉缓和",en:"Sorry about that.",zh:"不好意思，刚才那个抱歉。",scene:"小失误后快速缓和。",tip:"about that 连读，that 轻落。",example:"Sorry about that, I clicked the wrong link.",keys:["sorry","about"]},
  {id:"soften-02",group:"道歉缓和",en:"I didn't mean to.",zh:"我不是故意的。",scene:"解释自己没有恶意。",tip:"didn't mean 连读，mean 稍重。",example:"I didn't mean to interrupt you.",keys:["didn't","mean"]},
  {id:"soften-03",group:"道歉缓和",en:"Thanks for understanding.",zh:"谢谢你理解。",scene:"对方体谅你时。",tip:"thanks for 弱读，understanding 重音在 stand。",example:"I need to reschedule. Thanks for understanding.",keys:["thanks","understanding"]},
  {id:"soften-04",group:"道歉缓和",en:"No big deal.",zh:"没什么大不了。",scene:"让对方别把小事放大。",tip:"big deal 两个词都要清楚。",example:"A: I spilled a little. B: No big deal.",keys:["big","deal"]},
  {id:"soften-05",group:"道歉缓和",en:"It happens.",zh:"这种事难免。",scene:"安慰别人犯小错。",tip:"happens 第一音节重，语气轻。",example:"A: I missed the bus. B: It happens.",keys:["happens"]},
  {id:"soften-06",group:"道歉缓和",en:"I appreciate your patience.",zh:"感谢你耐心等待。",scene:"正式但不僵硬，适合延迟后。",tip:"appreciate 重音在 pre，patience 第一音节重。",example:"I appreciate your patience while I check this.",keys:["appreciate","patience"]},
  {id:"soften-07",group:"道歉缓和",en:"Let's start over.",zh:"我们重新来过吧。",scene:"对话乱了、误会了，重新开始。",tip:"start over 连读，over 轻落。",example:"This got confusing. Let's start over.",keys:["start","over"]},
  {id:"soften-08",group:"道歉缓和",en:"Sorry to keep you waiting.",zh:"抱歉让你久等了。",scene:"迟到、回复慢、处理久了。",tip:"keep you 像 kee-pyou，waiting 第一音节重。",example:"Sorry to keep you waiting. I'm ready now.",keys:["sorry","waiting"]},
  {id:"soften-09",group:"道歉缓和",en:"I should have said that differently.",zh:"我刚才应该换个说法。",scene:"修正自己表达不当。",tip:"should have 可弱读成 should've，differently 重音在 diff。",example:"I should have said that differently. Let me try again.",keys:["should","said","differently"]},
  {id:"opinion-01",group:"表达观点",en:"I feel like...",zh:"我感觉……",scene:"说主观看法，比 I think 更柔和。",tip:"feel like 连读，后面自然接观点。",example:"I feel like we should keep it simple.",keys:["feel","like"]},
  {id:"opinion-02",group:"表达观点",en:"To be honest.",zh:"说实话。",scene:"准备讲真实感受或不同意见。",tip:"to be 弱读，honest 的 h 不发音。",example:"To be honest, I'm not a fan of it.",keys:["honest"]},
  {id:"opinion-03",group:"表达观点",en:"In my experience.",zh:"以我的经验来看。",scene:"分享经验而不是绝对判断。",tip:"experience 重音在 peer。",example:"In my experience, shorter messages work better.",keys:["experience"]},
  {id:"opinion-04",group:"表达观点",en:"I'm not sure about that.",zh:"这个我不太确定。",scene:"委婉表达保留意见。",tip:"not sure about 连起来，that 轻收。",example:"I'm not sure about that deadline.",keys:["sure","about"]},
  {id:"opinion-05",group:"表达观点",en:"That's a good point.",zh:"这个点说得好。",scene:"认可对方观点。",tip:"good point 连读，point 收 t。",example:"That's a good point. We should test it first.",keys:["good","point"]},
  {id:"opinion-06",group:"表达观点",en:"I wouldn't say that.",zh:"我倒不会那么说。",scene:"温和反驳，不直接说你错了。",tip:"wouldn't say 连读，that 短收。",example:"I wouldn't say that. It's more complicated.",keys:["wouldn't","say"]},
  {id:"opinion-07",group:"表达观点",en:"I get where you're coming from.",zh:"我理解你的出发点。",scene:"先共情，再表达不同想法。",tip:"where you're 连读，coming from 稳住节奏。",example:"I get where you're coming from, but I disagree.",keys:["get","coming"]},
  {id:"opinion-08",group:"表达观点",en:"It depends.",zh:"看情况。",scene:"答案不是绝对时。",tip:"depends 重音在 pends。",example:"A: Is it worth it? B: It depends.",keys:["depends"]},
  {id:"opinion-09",group:"表达观点",en:"Here's the thing.",zh:"问题是这样的。",scene:"准备解释关键点。",tip:"here's the 连读，thing 重一点。",example:"Here's the thing: we don't have the budget.",keys:["thing"]},
  {id:"bridge-01",group:"转场接话",en:"By the way.",zh:"顺便说一下。",scene:"自然切到另一个话题。",tip:"by the 弱读，way 稍重。",example:"By the way, did you get my message?",keys:["way"]},
  {id:"bridge-02",group:"转场接话",en:"Speaking of that.",zh:"说到这个。",scene:"接住刚才话题，展开相关内容。",tip:"speaking 重音在 speak，of that 连读。",example:"Speaking of that, I have a quick question.",keys:["speaking","that"]},
  {id:"bridge-03",group:"转场接话",en:"Anyway.",zh:"总之，先这样。",scene:"把话题拉回来或收尾。",tip:"anyway 重音在 way。",example:"Anyway, let's get back to work.",keys:["anyway"]},
  {id:"bridge-04",group:"转场接话",en:"Before I forget.",zh:"趁我还没忘。",scene:"插入一个重要提醒。",tip:"before I 连读，forget 重音在 get。",example:"Before I forget, your package arrived.",keys:["before","forget"]},
  {id:"bridge-05",group:"转场接话",en:"One more thing.",zh:"还有一件事。",scene:"补充最后一点。",tip:"one more 连读，thing 轻收。",example:"One more thing: don't share the link yet.",keys:["one","thing"]},
  {id:"bridge-06",group:"转场接话",en:"That reminds me.",zh:"这倒提醒我了。",scene:"由对方话题联想到另一件事。",tip:"reminds 重音在 minds。",example:"That reminds me, I need to call Alex.",keys:["reminds","me"]},
  {id:"bridge-07",group:"转场接话",en:"Back to what you said.",zh:"回到你刚才说的。",scene:"拉回前面一个观点继续说。",tip:"back to 弱读，said 收短。",example:"Back to what you said, I think you're right.",keys:["back","said"]},
  {id:"bridge-08",group:"转场接话",en:"On a different note.",zh:"换个话题。",scene:"礼貌转到不相关的话题。",tip:"different 第一音节重，note 清楚。",example:"On a different note, how was your trip?",keys:["different","note"]},
  {id:"bridge-09",group:"转场接话",en:"Let's circle back.",zh:"我们回头再说/回到这个点。",scene:"会议或讨论中暂时搁置再回来。",tip:"circle back 节奏清楚，back 重。",example:"Let's circle back after we see the numbers.",keys:["circle","back"]}
];
